name = "{{ manifest.name }}"
version = "{{ manifest.version }}"

{% if "metadata" in manifest %}
[metadata]
{%- for k, v in manifest.metadata.items() %}
{{ k }} = "{{ v }}"
{%- endfor -%}
{% endif %}

[execution-environment]
{%- if 'entrypoint' in manifest['execution-environment'] %}
entrypoint = "{{ manifest['execution-environment'].entrypoint }}"
{%- endif %}
type = "{{ manifest['execution-environment'].type }}"

{% if manifest.attachments -%}
[attachments]

{%- for name, attachment in manifest.attachments.items() %}

[attachments.{{name}}]
path = "attachments/{{ name }}"

[attachments.{{name}}.checksums]
{%- for k, v in attachment.checksums.items() %}
{{ k }} = "{{ v }}"
{%- endfor -%}

{% if "metadata" in attachment %}
[attachments.{{name}}.metadata]
{%- for k, v in attachment.metadata.items() %}
{{ k }} = "{{ v }}"
{%- endfor -%}
{%- endif %}

{% endfor -%}

{%- endif %}

[code]
path = "{{manifest.code.path}}"

[code.checksums]
{%- for k, v in manifest.code.checksums.items() %}
{{ k }} = "{{ v }}"
{%- endfor -%}
