[package]
name = "turbo-isl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.93", features = ["full"] }

[dev-dependencies]
wasmtime = "0.36"
parking_lot = "0.12.1"
