[package]
name = "compiler"
version = "0.1.0"
authors = ["Goodbye Kansas Pipeline team <pipeline@goodbyekansas.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic-build = "0.2"
structopt = "0.3"
