name = "{{ manifest.name }}"
version = "{{ manifest.version }}"

{% if "metadata" in manifest %}
[metadata]
{% for k, v in manifest.metadata.items() %}
{{ k }} = "{{ v }}"
{% endfor %}
{% endif %}

[runtime]
{% if 'entrypoint' in manifest['runtime'] %}
entrypoint = "{{ manifest['runtime'].entrypoint }}"
{% endif %}
type = "{{ manifest['runtime'].type }}"

{% if "inputs" in manifest %}
[inputs]
{% for name, input in manifest.inputs.items() %}
[inputs.{{name}}]
type = "{{input.type}}"
required = {{ "true" if "required" in input and input.required else "false" }}
description = "{{input.description}}"
{% endfor %}
{% endif %}

{% if "outputs" in manifest %}
[outputs]
{% for name, output in manifest.outputs.items() %}
[outputs.{{name}}]
type = "{{output.type}}"
description = "{{output.description}}"
{% endfor %}
{% endif %}

{% if manifest.attachments %}
[attachments]

{% for name, attachment in manifest.attachments.items() %}
[attachments.{{name}}]
path = "attachments/{{ name }}"
[attachments.{{name}}.checksums]
{% for k, v in attachment.checksums.items() %}
{{ k }} = "{{ v }}"
{% endfor %}
{% if "metadata" in attachment %}
[attachments.{{name}}.metadata]
{% for k, v in attachment.metadata.items() %}
{{ k }} = "{{ v }}"
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}

[code]
path = "{{manifest.code.path}}"
[code.checksums]
{% for k, v in manifest.code.checksums.items() %}
{{ k }} = "{{ v }}"
{% endfor %}
