[package]
name = "firm-types"
version = "0.1.0"
authors = ["GBK Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
prost = "0.6"

firm-protocols = { path = "nix-deps/rust-firm-protocols" }
