[package]
name = "wasi-python-shims"
version = "1.0.0"
authors = ["GBK Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
lazy_static = "1"

[build-dependencies]
cbindgen = "0.18"
tempfile = "3"

