[package]
name = "bendini"
version = "0.1.0"
authors = ["GBK Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
async-stream = "0.3"
atty = "0.2"
futures = "0.3"
indicatif = "0.15"
prost = "0.7"
rand = "0.8"
regex = "1"
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
toml = "0.5"
tower = "0.4"
url = "2"

firm-types = { version = "0.1", registry = "nix" }
tonic-middleware = { version = "0.1", registry = "nix" }

[dev-dependencies]
tempfile = "3"
