[package]
name = "bendini"
version = "0.1.0"
authors = ["Dane Bettis <dane.bettis@goodbyekansas.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.6"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
termcolor = "1"
thiserror = "1"
tokio = { version = "0.2", features = ["rt-threaded"] }
toml = "0.5"
uuid = { version = "0.8", features = ["v4"] }
gbk-protocols = { path = "nix-deps/rust-protobuf-definitions" }
