[package]
name = "tonic-middleware"
version = "0.1.0"
authors = ["GBK Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2018"

[dependencies]
http = "0.2"

firm-protocols = { version = "0.1.0", registry = "nix" }

