[package]
name = "firm-types"
version = "1.0.0"
authors = ["GBK Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2021"

[dependencies]
thiserror = "1"
firm-protocols = { version = "1.0.0", registry = "nix" }
