[package]
name = "firm-types"
version = "1.0.0"
authors = ["GBK Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2018"

[dependencies]
thiserror = "1"
prost = "0.7"
firm-protocols = { version = "1.0.0", registry = "nix" }
