[package]
name = "firm-installer"
version = "0.1.0"
edition = "2018"

[dependencies]
flate2 = "1"
structopt = "0.3"
tar = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = { version="0.3", features=["winsvc", "impl-default"] }
windows-acl = "0.3"
winreg = "0.9"
winlog = "0.2.6"
