[package]
name = "wasi-python-shims"
version = "0.1.0"
authors = ["GBK Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.15"
