[package]
name = "avery"
version = "0.1.0"
authors = ["GBK Pipeline Team <pipeline@goodbyekansas.com>"]
edition = "2018"

[dependencies]
async-stream = "0.3"
config = "0.10"
flate2 = "1"
futures = "0.3"
hex = "0.4"
prost = "0.7"
regex = "1"
semver = "0.11"
serde = "1"
sha2 = "0.9"
slog = "2"
slog-async = "2"
slog-term = "2"
structopt = "0.3"
tar = "0.4"
tempfile = "3"
thiserror = "1"

# use `=` here to match our fork belowf
# TODO: update fork to 1.4.0
tokio = { version = "=1.3.0", features = ["rt-multi-thread", "time", "macros", "net", "signal"] }

toml = "0.5"
typetag = "0.1"
url = "2"
uuid = { version = "0.8", features = ["serde", "v4"] }
wasmer-wasi = "1"
wasmer = "1"

firm-types = { version = "0.1", registry = "nix" }
tonic-middleware = { version = "0.1", registry = "nix" }

[target.'cfg(unix)'.dependencies]
users = "0.11"

[target.'cfg(windows)'.dependencies]
winapi = "0.3"

# our own version of tokio 1.3.0 with named pipes
[patch.crates-io]
tokio = {  git = "https://github.com/goodbyekansas/tokio.git", branch="named-pipes-1.3.0" }

