name: Checks

on: [push]

jobs:
  format-nix:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12

    - name: Setup ssh agent and ssh options
      env:
        CI_ACCESS_KEY: ${{ secrets.NEDRYLAND_ACCESS_KEY }}
      run: .github/workflows/setup-ssh.sh .github/workflows/ssh-config

    - name: Format the Firm 💋
      run: ./.github/workflows/with-nedryland-pkgs.sh nix-shell -p nixpkgs-fmt --command "nixpkgs-fmt . --check"

  build-package-with-checks:
    name: "Build all components with checks"
    runs-on: ubuntu-latest

    steps:

    - name: Clone the repo
      uses: actions/checkout@v2

    - name: Setup ssh agent and ssh options
      env:
        CI_ACCESS_KEY: ${{ secrets.NEDRYLAND_ACCESS_KEY }}
      run: .github/workflows/setup-ssh.sh .github/workflows/ssh-config

    - name: Set up nix builders ssh connection
      run: .github/workflows/setup-builders-ssh.sh

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Create Nix configuration
      run: |
        mkdir -p ~/.config/nix
        cp .github/workflows/nix.conf ~/.config/nix/nix.conf

    - name: Setup cachix
      uses: cachix/cachix-action@v7
      with:
        name: firm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Generate list of derivations to build
      run: nix-instantiate -A packageWithChecks --add-root ./derivations/drv --indirect

    - name: Create Github checks for each derivation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: .github/workflows/github-package-status.bash pre ${{ github.repository }} ${{ github.sha }} ${{ github.job }} ./derivations

    - name: Build all derivations
      run: nix build --keep-going -L ./derivations/* --show-trace --max-jobs 0

    - name: Finish Github checks for each derivation
      if: ${{ always() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: .github/workflows/github-package-status.bash post ${{ github.repository }} ./derivations
