name: Checks

on: [push]

jobs:
  format-nix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Format the Firm 💋
      run:  nix-shell -p nixpkgs-fmt --command "nixpkgs-fmt . --check"

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [
          avery,
          bendini,
          lomax,
          rustGbkUtils,
        ]

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.NEDRYLAND_ACCESS_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - uses: actions/checkout@v2.0.0
    - name: Install Nix
      uses: cachix/install-nix-action@v8
    - name: Remove rustup since it interferes with the build
      run: rustup self uninstall -y
    - name: Disable Nix sandboxing
      run: |
        mkdir -p ~/.config/nix
        echo "sandbox = false" > ~/.config/nix/nix.conf
    - name: Create Cache Folder
      run: |
        sudo mkdir -p /var/cache/nedryland-rust
        sudo chown $(id -un):nixbld /var/cache/nedryland-rust
        sudo chmod g+rwx /var/cache/nedryland-rust
    - name: Cache rust output
      uses: actions/cache@v1.1.2
      with:
        path: /var/cache/nedryland-rust
        key: rust-v3-${{ runner.os }}-${{matrix.component}}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          rust-v3-${{ runner.os }}-${{matrix.component}}-
    - name: Build, test and cache ${{ matrix.component }} package
      uses: cachix/cachix-action@v5
      with:
        name: firm
        nixBuildArgs: --verbose --show-trace
        attributes: "${{ matrix.component }}.packageWithChecks"
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Set correct permissions of cache directory
      run: sudo chmod -R o+r /var/cache/nedryland-rust
    - name: Cache hack to avoid empty cache
      run: sudo rmdir /var/cache/nedryland-rust || true
