name: Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [services/avery/avery.nix, clients/bendini/bendini.nix, clients/lomax/lomax.nix]

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Remove rustup since it interferes with the build
      run: rustup self uninstall -y
    - name: Disable Nix sandboxing
      run: |
        mkdir -p ~/.config/nix
        echo "sandbox = false" > ~/.config/nix/nix.conf
    - name: Build, test and cache ${{ matrix.component }} package
      uses: cachix/cachix-action@v3
      with:
        name: firm
        file: "${{ matrix.component }}"
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
