name: Checks

on: [push]

jobs:
  format-nix:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Format the Firm 💋
      run:  nix-shell -p nixpkgs-fmt --command "nixpkgs-fmt . --check"

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [
          avery,
          bendini,
          lomax,
        ]

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.NEDRYLAND_ACCESS_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - uses: actions/checkout@v2.0.0
    - name: Install Nix
      uses: cachix/install-nix-action@v8
    - name: Remove rustup since it interferes with the build
      run: rustup self uninstall -y
    - name: Disable Nix sandboxing
      run: |
        mkdir -p ~/.config/nix
        echo "sandbox = false" > ~/.config/nix/nix.conf
    - name: Build, test and cache ${{ matrix.component }} package
      uses: cachix/cachix-action@v5
      with:
        name: firm
        attributes: "${{ matrix.component }}.packageWithChecks"
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
